
/*para proteger los objetos los ponemos como constante para protegerlos*/

//OBJETO LITERAL
/* let user = {    //object
    nombre: 'pepe',
    apellido: 'perez',
    direccion: {
        calle: 'goya',
        ciudad: 'madrid',
        c_postal: '28033'
    }, 

    edad: 23,
    isCasado: true
    
console.log(typeof user) //llama al objeto entero
user.cargo = "CEO"

console.log(user) */

 
//* /**********************************************OTROS TIPODE DE OBJETOS***************************** */

//ARRAY
/* 
let aDatos = [12, 23, 45, 45, 87]
let aDatosChungo = [12, 'pepe', true, null, undefined]

console.log(aDatos[1])

aDatos[15] = 30
console.log(aDatos) */


/* aUsuarios = [  ----------->NO ME SALE, quiero crear un array de objetos
    {nombre: 'pepe',
    apellido: 'perez',
    direccion : {
        calle : '',
        ciudad : '',
        c_postal : ''},
        
        { edad: 23,
            isCasado: true
        }
]
 */


 console.log (typeof user)  

//*******************************************************

//FUNCTION , METHOD, CONSTRUCTOR

/* let fecha = new Date()
let exp = new RegExp()
let error = new Error ()

Math.cos (90)
JSON.parse () */




